name: dotnet package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    - name: Install dependencies
      run: dotnet restore CodeWars/CodeWars.sln
    - name: Build
      run: dotnet build CodeWars/CodeWars.Tests/CodeWars.Tests.csproj --configuration Release --no-restore 
    - name: Test
      run: dotnet test CodeWars/CodeWars.Tests/CodeWars.Tests.csproj --no-restore --verbosity normal
